[package]
name = "invaders_in_asterofield"
version = "0.6.0"
authors = ["pyweeker working from forks"]
edition = "2021"

[dependencies]
bevy = "0.6.0"
rand = "0.8"
heron = { version = "1.0.1-rc.1" , features=["2d"]}
